### ISSUE TITLE
metric

### ISSUE THREAD

**Issue by xihuanliuliu** [rohit9934/DRIVE-Digital-Retinal-Images-for-Vessel-Extraction#1]
how to implement F1. acc ?

**Comment by rohit9934** [comment]
Can you please tell your issue in detail?

**Comment by xihuanliuliu** [comment]
How to implement evaluation metrics F1-Score, Sensitivity, Specificity and Accuracy

**Comment by xihuanliuliu** [comment]
How to implement evaluation metrics F1-Score, Sensitivity, Specificity and Accuracy  in your segmentation_metric.py

**Comment by rohit9934** [comment]
By using precision and recall calculated in the file in line 76. Moreover, i have already calculate all of the confusion matrix values, It's now just bunch of formulas to use.
