### ISSUE TITLE
Configuration 

### ISSUE THREAD

**Issue by aikar-jidu** [rohit9934/DRIVE-Digital-Retinal-Images-for-Vessel-Extraction#2]
Can you please provide some information about the running machine? GPU, OS...
Thanks,

**Comment by rohit9934** [comment]
Sorry about Late reply, OS was windows and GPU was NVIDIA DGX. This model was run on 50 GB alloted GPU. but as this is binary classificaiton task, you may need alot less.

**Comment by tphankr** [comment]
> Sorry about Late reply, OS was windows and GPU was NVIDIA DGX. This model was run on 50 GB alloted GPU. but as this is binary classificaiton task, you may need alot less.

Please, tell us. Which **tensorflow-gpu, keras, python versions** did you use for your environment? Thanks.
